name = "IsingModel"
uuid = "a158bd23-0110-41e7-858f-69697620f671"
authors = ["Jacob_Moxley <jacobcmoxley@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6.6"
